// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating a vibrant and visually appealing color palette for the food in the game using AI.
 *
 * - generateFoodColorPalette - A function that generates a list of colors for the food.
 * - GenerateFoodColorPaletteInput - The input type for the generateFoodColorPalette function.
 * - GenerateFoodColorPaletteOutput - The return type for the generateFoodColorPalette function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFoodColorPaletteInputSchema = z.object({
  count: z.number().describe('The number of colors to generate.'),
});
export type GenerateFoodColorPaletteInput = z.infer<typeof GenerateFoodColorPaletteInputSchema>;

const GenerateFoodColorPaletteOutputSchema = z.array(z.string().describe('A CSS color hex code.')).describe('A list of colors for the food.');
export type GenerateFoodColorPaletteOutput = z.infer<typeof GenerateFoodColorPaletteOutputSchema>;

export async function generateFoodColorPalette(input: GenerateFoodColorPaletteInput): Promise<GenerateFoodColorPaletteOutput> {
  return generateFoodColorPaletteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFoodColorPalettePrompt',
  input: {schema: GenerateFoodColorPaletteInputSchema},
  output: {schema: GenerateFoodColorPaletteOutputSchema},
  prompt: `You are a color palette generator that produces a list of vibrant and visually appealing CSS color hex codes for food items in a game.\n\nGenerate {{count}} colors.\n\nOutput should be a JSON array of hex codes. For example: ["#ff0000", "#00ff00", "#0000ff"]`,
});

const generateFoodColorPaletteFlow = ai.defineFlow(
  {
    name: 'generateFoodColorPaletteFlow',
    inputSchema: GenerateFoodColorPaletteInputSchema,
    outputSchema: GenerateFoodColorPaletteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
